#!/usr/bin/expect
set timeout 300
spawn ssh -o StrictHostKeyChecking=no root@106.14.32.99
expect "password:"
send "jQ5nyV\$GYquHC#YgC62U&p252sss\r"
expect "# "
send "cd /var/www/wedding-game\r"
expect "# "
send "tar -xzf docker-deploy.tar.gz\r"
expect "# "
send "ls -la\r"
expect "# "
send "docker-compose up -d --build\r"
expect "# "
send "sleep 10\r"
expect "# "
send "docker ps\r"
expect "# "
send "docker logs wedding-golden-egg-game\r"
expect "# "
send "exit\r"
expect eof
